jobs:
  - deployment: FirewallRulesDeploy
    environment: "Firewall Rules Test"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: AzurePowerShell@5
              displayName: Deploy Azure Firewall Default Rules Primary
              inputs:
                azurePowerShellVersion: latestVersion
                pwsh: true
                azureSubscription: $(azureServiceConnection)
                scriptType: filePath
                scriptArguments: "-SubscriptionId $(connectivitySubID) -ResourceGroupName $(primaryHubRGName) -FirewallPolicyName $(azureFirewallPrimaryPolicyName)"
                scriptPath: "./src/Invoke-DeployFirewallPolicyRules.ps1"
            - task: AzurePowerShell@5
              condition: ne(variables.azureFirewallSecondaryPolicyName, '')
              displayName: Deploy Azure Firewall Default Rules DR
              inputs:
                azurePowerShellVersion: latestVersion
                pwsh: true
                azureSubscription: $(azureServiceConnection)
                scriptType: filePath
                scriptArguments: '-SubscriptionId $(connectivitySubID) -ResourceGroupName $(secondaryHubRGName) -FirewallPolicyName $(azureFirewallSecondaryPolicyName) -PolicyCsvPath "./csv/FirewallRulesDR.csv"'
                scriptPath: "./src/Invoke-DeployFirewallPolicyRules.ps1"