trigger: none

variables:
  - group: alz
  - name: azureServiceConnection
    value: "wif-ado-prod"

pool:
  vmImage: "Ubuntu-Latest"

stages:
  - stage: firewallRulesDeploy
    displayName: "Firewall Rules Deploy"
    jobs:
      - template: "templates/firewallRulesDeploy.yaml"